---
title: "Wild boar movement: Analysis of scare off measures"
author: "Marina Mariotto & Melina Oldorf"
date: "14 6 2021"
output: html_document
---
## Background & Research Goal 
Since the wild boar (Sus scrofa) population increased consistently in whole Europe, but also in Switzerland in the 1960s and 1970s, the population of wild boar stayed at a quite high number since the 1980s (Massei et al. 2015). These high numbers of wild boars originate likely because of low impact of recreational hunting to wild boar population growth, mild winters, reforestation, intensification of crop production, supplementary feeding and compensatory population responses of wild boar to hunting pressure (Massei et al. 2015, Geisser 2005). Since crop production intensified and agricultural crops provide an optimal and easily accessible food source for wild boar, the damage of crop fields and therefore also financial loss for the farmers increased (Suter et al. 2018). In the past these damages lead to increased conflicts with farmers. To lower these human-wildlife conflicts, several prevention methods exist, whereas electric fences and scare off shots showed to be the most effective ones (Suter & Eyholzer 2010), nevertheless tend both methods to be quite time consuming and very costly (Suter 2013, Suter & Eyholzer 2010). To improve the situation for all involved and to create more cost-effective and practical methods, scare-off measures were developed, implemented, and monitored in the canton Bern (Suter, 2013, Suter 2018). To evaluate the success of the scare-off measures, GPS data from .... wild boars were analysed regarding their movement over time in combination with the reaction towards the scare-off measures.  This study aims to analyse, with the program R, the statistical success rate of the scare-off measures. 

### Research question
- Can the effectiveness of the wild boar scare-off measures sufficiently be detected and a success rate calculated by analysing the movement of the wild boar?
- Can a dependency between the effectiveness of the wild boar scare-off measures, the hunting pressure(weak&medium) as well the intensity of the scare-off measures be detected? 


## Data and Methods

### Data
The data was collected within the scope of the ZHAW project "Prävention von Wildschweinschäden
in der Landwirtschaft und Management von Wildschweinen in Schutzgebieten" conducted by S. Suter, S.Stoller and B. Sigrist in 2018. The provided data of the wild boars contained an investigation period of around two and a half years and each data point was attributed with a TierID, TierName, CollarID, Sex, Weight and Study area. Additionally movement data was provided for each wild boar individual containing TierID, TierName, CollarID, Date and Time of the recorded data point as well as Coordinates, time of day and moon illumination at the time of recording. The provided data for the scare-off measures consists of the coodrinates, where they were installed and the information when and how they were operated.

### Pre-processing 


calculated times for dawn and dusk for every day each Schreck was running
calculated distance of wild boar to scare off measures
calculate speed

### Methods
Auf Normalverteilung und Varianzhomogenität getestet. Alpha = 0.05
statistical test

### Limitations
The given data limits the analysis in a few way. The recorded movement of the wildboar is only given in an interval of 15 minutes. Therefore, a reaction to the scare-off measure might not be recorded at all as it might have happended in the 15 minutes between the recordings. The operational data of the scare-off measures contain the information on what date the scare-off measures were started and stopped and that they started every evening once it was dark enough, which was measured with a light sensor. However, the exact time when they went off to scare-off the wild boar was not recorded. That makes it difficult to draw a causality between scare-off measure and wild boar movement.
Jagdintensität mitreinnehmen. --> Diese Frage können wir mit unseren Daten nicht beantworten.

Limitations of the methods:

## Results
```{r, include = FALSE}
library(readr)        # to import tabular data (e.g. csv)
library(dplyr)        # to manipulate (tabular) data
library(ggplot2)      # to visualize data
library(lubridate)    # To handle dates and times
devtools::install_github("ComputationalMovementAnalysis/ComputationalMovementAnalysisData") # getting data from R Package
library(ComputationalMovementAnalysisData) #Wild boar data is on that package
library(sf) # encoding spatial vector data 
library(ggmap)
library(maps)
library(mapdata)
library(suncalc)
library(rgdal)
library(spatialrisk)
library(purrr)
```



## Discussion

## References
Geisser, H. & Reyer, H.-U. 2005. The influence of food and temperature on population density of wild 	boar Sus scrofa in the Thurgau (Switzerland). Journal of Zoology 267: 89-96
Massei, G. Kindberg, J. Licoppe, A. Gačić, D. Šprem, N. Kamler, J. Baubet, E. Hohmann, U. Monaco, A. 	Ozoliš, J. Cellina, S. Podgórski, T. Fonseca, C. Markov, N. Pokorny, B. Rosell, C. Náhlik, A. 2015. 	Wild boar populations up, numbers of hunters down? A review of trends and implications for 	Europe. Pest Management Science 71: 492- 500
Suter, S.M. & Eyholzer, R. 2010. Interkantonales Wildschweinprojekt FR-BE-VD, Räumliche und 	zeitliche Habitatnutzung, Schäden an landwirtschaftlichen Kulturen und Einfluss der Jagd auf 	das Raumverhalten der Wildschweine am Südostufer des Neuenburgersees, WLS.CH im 	Auftrag der Kantone FR/BE/VD und des BAFU
Suter, S.M. 2013. Forschungsprojekt Prävention von Wildschweinschäden in der 	Landwirtschaft. WILMA/ZHAW 
Suter, S.M., Stoller, S., Sigrist, B. 2018. Prävention von Wildschweinschäden in der Landwirtschaft und 	Management von Wildschweinen in Schutzgebieten – Schlussbericht. Projektstand 31.01.2018


